name: CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - run: sudo rm -rf /opt&
      - uses: actions/checkout@v4
      - uses: paolino/dev-assets/setup-nix@v0.0.1
        with:
          cachix-auth-token: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Build executable
        run: nix --quiet build .#csmt
      - name: Build docker image
        run: nix --quiet build .#docker-image -o csmt-image
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: csmt-image
          path: csmt-image
      - name: Build appImage artifact
        run: nix --quiet bundle --bundler github:ralismark/nix-appimage .#csmt -o csmt.AppImage
      - name: Upload appImage artifact
        uses: actions/upload-artifact@v4
        with:
          name: csmt-appImage
          path: csmt.AppImage
      - name: Build rpm artifact
        run: nix --quiet bundle --bundler github:NixOS/bundlers#toRPM -o csmt.rpm
      - name: Upload rpm artifact
        uses: actions/upload-artifact@v4
        with:
          name: csmt-rpm
          path: csmt.rpm
      - name: Build deb artifact
        run: nix --quiet bundle --bundler github:NixOS/bundlers#toDEB -o csmt.deb
      - name: Upload deb artifact
        uses: actions/upload-artifact@v4
        with:
          name: csmt-deb
          path: csmt.deb
  unit:
    name: Run unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: paolino/dev-assets/setup-nix@v0.0.1
        with:
          cachix-auth-token: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Run Tests
        run: nix --quiet run .#unit-tests
  bench:
    name: Run Benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: paolino/dev-assets/setup-nix@v0.0.1
        with:
          cachix-auth-token: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Run Benchmarks
        run: nix --quiet run .#bench
  formatting:
    name: Check code formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: paolino/dev-assets/setup-nix@v0.0.1
        with:
          cachix-auth-token: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Check Formatting
        run: nix --quiet develop -c just format